# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static

  # Remove firebase from iOS build entirely
  flutter_deps_path = File.join(File.dirname(File.realpath(__FILE__)), '..', '.flutter-plugins-dependencies')
  if File.exist?(flutter_deps_path)
    require 'json'
    deps = JSON.parse(File.read(flutter_deps_path))
    if deps['plugins'] && deps['plugins']['ios']
      deps['plugins']['ios'].reject! { |p| p['name'].start_with?('firebase') }
      File.write(flutter_deps_path, JSON.generate(deps))
    end
  end

  # Remove Firebase from GeneratedPluginRegistrant.m
  generated_registrant_path = File.join(File.dirname(File.realpath(__FILE__)), 'Runner', 'GeneratedPluginRegistrant.m')
  if File.exist?(generated_registrant_path)
    content = File.read(generated_registrant_path)
    content = content.gsub(/#if __has_include\(<firebase_core.*?\n#endif\n/m, '')
    content = content.gsub(/#if __has_include\(<firebase_messaging.*?\n#endif\n/m, '')
    content = content.gsub(/^.*\[FLTFirebaseCorePlugin registerWithRegistrar:.*$\n/, '')
    content = content.gsub(/^.*\[FLTFirebaseMessagingPlugin registerWithRegistrar:.*$\n/, '')
    File.write(generated_registrant_path, content)
  end

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
